[preprocessor.embedify]

[book]
authors = ["EsgalMythborn"]
language = "en"
multilingual = false
src = "src"
title = "Esgal Mythborn"

[output.html]
default-theme = "Light"
preferred-dark-theme = "Navy"
smart-punctuation = true
